name:                practice
version:             0.1.0.0
github:              "matonix/atcoder"
license:             BSD3
author:              "maton"
maintainer:          "automatonix@gmail.com"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  a:
    main:                Main.hs
    source-dirs:         a

executables:
  b:
    main:                Main.hs
    source-dirs:         b

executables:
  c:
    main:                Main.hs
    source-dirs:         c

executables:
  d:
    main:                Main.hs
    source-dirs:         d