name: library
version: '0.1.0'
author: maton
maintainer: automatonix@gmail.com

dependencies:
- base >= 4.7 && < 5
# atcoder haskell resources
# https://github.com/haskell-jp/atcoder-haskell-resources/blob/master/Import.hs
- QuickCheck
- array
- attoparsec
- bytestring
- containers
- deepseq
- fgl
- hashable
- mtl
- parallel
- parsec
- primitive
- random
- template-haskell
- text
- tf-random
- transformers
- unordered-containers
- vector
- extra
- integer-logarithms
- heaps
- lens
- massiv
- mono-traversable
- mutable-containers
- mwc-random
- psqueues
- reflection
- repa
- unboxing-vector
- utility-ht
- vector-algorithms
- vector-th-unbox
# user specific package
- hspec
- main-tester
- directory
- hspec-discover

ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

tests:
  library-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - library
    - hspec
