name:                abc142
version:             0.1.0.0
license:             BSD3
author:              maton
maintainer:          automatonix@gmail.com

source-dirs: .

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- mtl
- pretty
- text
- time
- transformers
- vector

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  a:
    main:                Main.hs
    source-dirs:         a
  b:
    main:                Main.hs
    source-dirs:         b
  c:
    main:                Main.hs
    source-dirs:         c
  d:
    main:                Main.hs
    source-dirs:         d
  e:
    main:                Main.hs
    source-dirs:         e
  f:
    main:                Main.hs
    source-dirs:         f
